# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forAsiento.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formAsiento(object):
    def setupUi(self, formAsiento):
        formAsiento.setObjectName("formAsiento")
        formAsiento.resize(294, 292)
        self.label = QtWidgets.QLabel(formAsiento)
        self.label.setGeometry(QtCore.QRect(50, 30, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(formAsiento)
        self.label_6.setGeometry(QtCore.QRect(50, 90, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.numeroAsiento = QtWidgets.QSpinBox(formAsiento)
        self.numeroAsiento.setGeometry(QtCore.QRect(130, 90, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numeroAsiento.setFont(font)
        self.numeroAsiento.setObjectName("numeroAsiento")
        self.label_7 = QtWidgets.QLabel(formAsiento)
        self.label_7.setGeometry(QtCore.QRect(50, 130, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.filaAsiento = QtWidgets.QLineEdit(formAsiento)
        self.filaAsiento.setGeometry(QtCore.QRect(100, 130, 71, 20))
        self.filaAsiento.setObjectName("filaAsiento")
        self.label_8 = QtWidgets.QLabel(formAsiento)
        self.label_8.setGeometry(QtCore.QRect(50, 180, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.disponibleAsiento = QtWidgets.QSpinBox(formAsiento)
        self.disponibleAsiento.setGeometry(QtCore.QRect(190, 180, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.disponibleAsiento.setFont(font)
        self.disponibleAsiento.setMaximum(1)
        self.disponibleAsiento.setObjectName("disponibleAsiento")
        self.enviarAsiento = QtWidgets.QPushButton(formAsiento)
        self.enviarAsiento.setGeometry(QtCore.QRect(90, 240, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.enviarAsiento.setFont(font)
        self.enviarAsiento.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.enviarAsiento.setInputMethodHints(QtCore.Qt.ImhNone)
        self.enviarAsiento.setCheckable(False)
        self.enviarAsiento.setAutoExclusive(False)
        self.enviarAsiento.setObjectName("enviarAsiento")

        self.retranslateUi(formAsiento)
        QtCore.QMetaObject.connectSlotsByName(formAsiento)

    def retranslateUi(self, formAsiento):
        _translate = QtCore.QCoreApplication.translate
        formAsiento.setWindowTitle(_translate("formAsiento", "Form"))
        self.label.setText(_translate("formAsiento", "Formulario de Asiento"))
        self.label_6.setText(_translate("formAsiento", "Numero:"))
        self.label_7.setText(_translate("formAsiento", "Fila:"))
        self.label_8.setText(_translate("formAsiento", "Disponibilidad:"))
        self.enviarAsiento.setText(_translate("formAsiento", "Enviar"))
