# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formTran.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formTran(object):
    def setupUi(self, formTran):
        formTran.setObjectName("formTran")
        formTran.resize(362, 290)
        self.label = QtWidgets.QLabel(formTran)
        self.label.setGeometry(QtCore.QRect(50, 30, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.montoTran = QtWidgets.QDoubleSpinBox(formTran)
        self.montoTran.setGeometry(QtCore.QRect(150, 180, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.montoTran.setFont(font)
        self.montoTran.setObjectName("montoTran")
        self.label_3 = QtWidgets.QLabel(formTran)
        self.label_3.setGeometry(QtCore.QRect(80, 180, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.fechaTran = QtWidgets.QDateEdit(formTran)
        self.fechaTran.setGeometry(QtCore.QRect(150, 90, 110, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fechaTran.setFont(font)
        self.fechaTran.setInputMethodHints(QtCore.Qt.ImhDate)
        self.fechaTran.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 8, 1), QtCore.QTime(0, 0, 0)))
        self.fechaTran.setObjectName("fechaTran")
        self.label_4 = QtWidgets.QLabel(formTran)
        self.label_4.setGeometry(QtCore.QRect(80, 90, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(formTran)
        self.label_5.setGeometry(QtCore.QRect(80, 130, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horaTran = QtWidgets.QTimeEdit(formTran)
        self.horaTran.setGeometry(QtCore.QRect(150, 130, 118, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.horaTran.setFont(font)
        self.horaTran.setObjectName("horaTran")
        self.enviarTran = QtWidgets.QPushButton(formTran)
        self.enviarTran.setGeometry(QtCore.QRect(120, 230, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.enviarTran.setFont(font)
        self.enviarTran.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.enviarTran.setInputMethodHints(QtCore.Qt.ImhNone)
        self.enviarTran.setCheckable(False)
        self.enviarTran.setAutoExclusive(False)
        self.enviarTran.setObjectName("enviarTran")

        self.retranslateUi(formTran)
        QtCore.QMetaObject.connectSlotsByName(formTran)

    def retranslateUi(self, formTran):
        _translate = QtCore.QCoreApplication.translate
        formTran.setWindowTitle(_translate("formTran", "Form"))
        self.label.setText(_translate("formTran", "Formulario de Transacciones"))
        self.label_3.setText(_translate("formTran", "Monto:"))
        self.label_4.setText(_translate("formTran", "Fecha:"))
        self.label_5.setText(_translate("formTran", "Hora:"))
        self.enviarTran.setText(_translate("formTran", "Enviar"))
