# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formFunciones.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formFunciones(object):
    def setupUi(self, formFunciones):
        formFunciones.setObjectName("formFunciones")
        formFunciones.resize(306, 218)
        self.label = QtWidgets.QLabel(formFunciones)
        self.label.setGeometry(QtCore.QRect(40, 10, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(formFunciones)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(formFunciones)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.fechaFunciones = QtWidgets.QDateEdit(formFunciones)
        self.fechaFunciones.setGeometry(QtCore.QRect(100, 70, 131, 20))
        self.fechaFunciones.setObjectName("fechaFunciones")
        self.horaFunciones = QtWidgets.QTimeEdit(formFunciones)
        self.horaFunciones.setGeometry(QtCore.QRect(100, 120, 131, 20))
        self.horaFunciones.setObjectName("horaFunciones")
        self.enviarFunciones = QtWidgets.QPushButton(formFunciones)
        self.enviarFunciones.setGeometry(QtCore.QRect(120, 160, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.enviarFunciones.setFont(font)
        self.enviarFunciones.setObjectName("enviarFunciones")

        self.retranslateUi(formFunciones)
        QtCore.QMetaObject.connectSlotsByName(formFunciones)

    def retranslateUi(self, formFunciones):
        _translate = QtCore.QCoreApplication.translate
        formFunciones.setWindowTitle(_translate("formFunciones", "Form"))
        self.label.setText(_translate("formFunciones", "Formulario de Funciones"))
        self.label_2.setText(_translate("formFunciones", "Fecha:"))
        self.label_3.setText(_translate("formFunciones", "Hora:"))
        self.enviarFunciones.setText(_translate("formFunciones", "Enviar"))
