# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formSala.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formSala(object):
    def setupUi(self, formSala):
        formSala.setObjectName("formSala")
        formSala.resize(308, 210)
        self.label = QtWidgets.QLabel(formSala)
        self.label.setGeometry(QtCore.QRect(60, 20, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(formSala)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.enviarFunciones = QtWidgets.QPushButton(formSala)
        self.enviarFunciones.setGeometry(QtCore.QRect(160, 210, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.enviarFunciones.setFont(font)
        self.enviarFunciones.setObjectName("enviarFunciones")
        self.label_3 = QtWidgets.QLabel(formSala)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.enviarSala = QtWidgets.QPushButton(formSala)
        self.enviarSala.setGeometry(QtCore.QRect(120, 170, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.enviarSala.setFont(font)
        self.enviarSala.setObjectName("enviarSala")
        self.numeroSala = QtWidgets.QSpinBox(formSala)
        self.numeroSala.setGeometry(QtCore.QRect(120, 80, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numeroSala.setFont(font)
        self.numeroSala.setObjectName("numeroSala")
        self.capacidadSala = QtWidgets.QSpinBox(formSala)
        self.capacidadSala.setGeometry(QtCore.QRect(140, 130, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.capacidadSala.setFont(font)
        self.capacidadSala.setObjectName("capacidadSala")

        self.retranslateUi(formSala)
        QtCore.QMetaObject.connectSlotsByName(formSala)

    def retranslateUi(self, formSala):
        _translate = QtCore.QCoreApplication.translate
        formSala.setWindowTitle(_translate("formSala", "Form"))
        self.label.setText(_translate("formSala", "Formulario de Sala"))
        self.label_2.setText(_translate("formSala", "Numero:"))
        self.enviarFunciones.setText(_translate("formSala", "Enviar"))
        self.label_3.setText(_translate("formSala", "Capacidad:"))
        self.enviarSala.setText(_translate("formSala", "Enviar"))
