# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formCali.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formCali(object):
    def setupUi(self, formCali):
        formCali.setObjectName("formCali")
        formCali.resize(400, 294)
        self.label = QtWidgets.QLabel(formCali)
        self.label.setGeometry(QtCore.QRect(70, 30, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(formCali)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.nombreCali = QtWidgets.QLineEdit(formCali)
        self.nombreCali.setGeometry(QtCore.QRect(140, 90, 231, 21))
        self.nombreCali.setObjectName("nombreCali")
        self.label_5 = QtWidgets.QLabel(formCali)
        self.label_5.setGeometry(QtCore.QRect(50, 160, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.descripcionCali = QtWidgets.QPlainTextEdit(formCali)
        self.descripcionCali.setGeometry(QtCore.QRect(160, 160, 211, 51))
        self.descripcionCali.setObjectName("descripcionCali")
        self.enviarCali = QtWidgets.QPushButton(formCali)
        self.enviarCali.setGeometry(QtCore.QRect(150, 240, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.enviarCali.setFont(font)
        self.enviarCali.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.enviarCali.setInputMethodHints(QtCore.Qt.ImhNone)
        self.enviarCali.setCheckable(False)
        self.enviarCali.setAutoExclusive(False)
        self.enviarCali.setObjectName("enviarCali")

        self.retranslateUi(formCali)
        QtCore.QMetaObject.connectSlotsByName(formCali)

    def retranslateUi(self, formCali):
        _translate = QtCore.QCoreApplication.translate
        formCali.setWindowTitle(_translate("formCali", "Form"))
        self.label.setText(_translate("formCali", "Formulario de Calificaciones"))
        self.label_2.setText(_translate("formCali", "Nombre:"))
        self.label_5.setText(_translate("formCali", "Descripción:"))
        self.enviarCali.setText(_translate("formCali", "Enviar"))
