# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'venta.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formVenta(object):
    def setupUi(self, formVenta):
        formVenta.setObjectName("formVenta")
        formVenta.resize(262, 174)
        self.label = QtWidgets.QLabel(formVenta)
        self.label.setGeometry(QtCore.QRect(30, 30, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(formVenta)
        self.label_3.setGeometry(QtCore.QRect(50, 80, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.totalVenta = QtWidgets.QDoubleSpinBox(formVenta)
        self.totalVenta.setGeometry(QtCore.QRect(120, 80, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.totalVenta.setFont(font)
        self.totalVenta.setObjectName("totalVenta")
        self.enviarVenta = QtWidgets.QPushButton(formVenta)
        self.enviarVenta.setGeometry(QtCore.QRect(80, 130, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.enviarVenta.setFont(font)
        self.enviarVenta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.enviarVenta.setInputMethodHints(QtCore.Qt.ImhNone)
        self.enviarVenta.setCheckable(False)
        self.enviarVenta.setAutoExclusive(False)
        self.enviarVenta.setObjectName("enviarVenta")

        self.retranslateUi(formVenta)
        QtCore.QMetaObject.connectSlotsByName(formVenta)

    def retranslateUi(self, formVenta):
        _translate = QtCore.QCoreApplication.translate
        formVenta.setWindowTitle(_translate("formVenta", "Form"))
        self.label.setText(_translate("formVenta", "Formulario de Venta"))
        self.label_3.setText(_translate("formVenta", "Total:"))
        self.enviarVenta.setText(_translate("formVenta", "Enviar"))
